### ISSUE TITLE
Express example

### ISSUE THREAD

**Issue by MatthijsKamstra** [haxiomic/dts2hx#70] opened 2020-10-27 21:21 UTC
I have downloaded your repo and used the express example. 

I update    `dts2hx` to version `0.10.7` --> `npm install dts2hx`

Used `npm install` to install dep.

when I build `haxe build.hxml` I get "Server.hx:13: characters 16-30 : express.Router is not a value"

**Comment by haxiomic** [comment] 2020-10-27 21:28
Tried this too and I cannot reproduce the issue, maybe check you're deleting .haxelib first to make sure you get a fresh copy

I'm using haxe 4.1.4

**Comment by MatthijsKamstra** [comment] 2020-10-27 22:08
`"dts2hx": "^0.14.6"` weird that my version was so much lower....

that fixed some... please keep this open... will investigate tomorrow...

**Comment by haxiomic** [comment] 2020-10-27 22:12
`package-lock.json` can keep a reference to the previously installed version, which is not obvious, I often delete it before `npm install` for a refresh

**Comment by haxiomic** [comment] 2020-11-07 17:31
Closing this as I think it's resolved with the package refresh?

**Closed by haxiomic** 2020-11-07 17:31 UTC

**Comment by MatthijsKamstra** [comment] 2020-11-09 11:16
sorry, I haven't gotten around to figuring out why it doesn't work

I will make a new issue when I do
