### ISSUE TITLE
Generating global externs without global prefix?

### ISSUE THREAD

**Issue by RblSb** [haxiomic/dts2hx#49] opened 2020-08-28 08:22 UTC
Is there is way to generate modular externs just like global, with `@:native` instead of `@:jsRequire`?

**Comment by haxiomic** [comment] 2020-08-28 15:10
If the externs declare global scope types then it will generate externs with `@:native` in a folder called `global`. Next time I work on this I plan to add a new flag `--mergeGlobal` so that does away with the prefix (see https://github.com/haxiomic/dts2hx/issues/18#issuecomment-631601369)

If the externs are missing `@:native` types and there's no `global` folder, then either:
- type definitions don't declare global types, a small modification to the .d.ts files can enable this
- generator is not seeing the global definitions for whatever reason

Which externs are you trying to convert?

**Comment by haxiomic** [comment] 2020-09-22 00:49
Closing as duplicate of #18

**Closed by haxiomic** 2020-09-22 00:49 UTC
